### ISSUE TITLE
publisher stops suddenly. (deadlock?)

### ISSUE THREAD

**Issue by caoyang1024** [nats-io/nats.net#645]
### Observed behavior

try to stress test nats, by sending 1000 msg/s each thread, with 1 - 100 different number of threads, when threads go higher, this situation happens more often.

### Expected behavior

looks to me like a deadlock, i can provide more info if needed.

![Snipaste_2024-10-05_18-19-57](https://github.com/user-attachments/assets/21942da2-706d-40d5-9648-9cb2ce59a710)

### Server and client version

"version": "2.10.21"
<PackageReference Include="NATS.Net" Version="2.4.0" />

**Comment by mtmk** [comment]
thanks for the report @caoyang1024 I'm suspecting potentially using semaphore might be causing this and thinking about switching to using a channel instead, but just speculating at the moment. If you could post a minimal console app program.cs and the server setup that would help a lot.

**Comment by caoyang1024** [comment]
@mtmk sure. here is my testing code. https://github.com/caoyang1024/stress-test.git

i'm running my NATS using docker locally.

```
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    image: nats
    ports:
      - "4223:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    ports:
      - "4224:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats
    external: true
```
